from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
FLAGS_DIR = PROJECT_ROOT / "src" / "flags"
assert FLAGS_DIR.exists(), f"Flags directory does not exist: {FLAGS_DIR}"
OVERVIEW_FILE = PROJECT_ROOT / "overview.generated.typ"

if __name__ == "__main__":

    ids = []
    for path in FLAGS_DIR.glob("*.svg"):
        ids.append(path.stem)

    doc = """
/// This file is auto-generated by `generate_overview.py`.
#import "lib.typ": flag

#set page(margin: 1cm)
#set align(center)
== Flags Overview


#grid(
columns: (3em,) * 12,
column-gutter: 3pt,
align: horizon + center,
rows: (2em),
row-gutter: 3pt,
stroke: (x, y) => {
    if calc.even(x) and x > 0 {
        (left: 1pt)
    }
},
"""

    for id in ids:
        doc += f'[`{id}`], flag("{id}"),\n'

    doc += "\n)"

    with OVERVIEW_FILE.open("w") as f:
        f.write(doc)
